### ISSUE TITLE
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

### ISSUE THREAD

**Issue by roniemartinez** [goose3/goose3#109]
Hi,

Encountered an error in the use of lxml: 
```
Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
Traceback (most recent call last):
  File "<redacted_path>/venv/lib/python3.6/site-packages/goose3/__init__.py", line 128, in crawler_wrapper
    article = crawler.crawl(crawl_candidate)
  File "<redacted_path>/venv/lib/python3.6/site-packages/goose3/crawler.py", line 132, in crawl
    return self.process(raw_html, parse_candidate.url, parse_candidate.link_hash)
  File "<redacted_path>/venv/lib/python3.6/site-packages/goose3/crawler.py", line 137, in process
    doc = self.get_document(raw_html)
  File "<redacted_path>/venv/lib/python3.6/site-packages/goose3/crawler.py", line 321, in get_document
    doc = self.parser.fromstring(raw_html)
  File "<redacted_path>/venv/lib/python3.6/site-packages/goose3/parsers.py", line 57, in fromstring
    doc = lxml.html.fromstring(html)
  File "<redacted_path>/venv/lib/python3.6/site-packages/lxml/html/__init__.py", line 875, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "<redacted_path>/venv/lib/python3.6/site-packages/lxml/html/__init__.py", line 761, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "src/lxml/etree.pyx", line 3234, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1871, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

The issue is similar to this: https://stackoverflow.com/questions/28534460/lxml-etree-xml-valueerror-for-unicode-string

**Comment by barrust** [comment]
I have been unable to reproduce this error. Are you still experiencing it? If so, what version of Goose3 are you using and can you provide the URL or HTML file and a code sample of how you are experiencing the issue?

**Comment by vprelovac** [comment]
@barrust @grangier here is how to reproduce

from goose3 import Goose
import requests
g=Goose()
article=g.extract(raw_html=requests.get("https://arxiv.org/abs/1907.09595").text)
