### ISSUE TITLE
Library does not working

### ISSUE THREAD

**Issue by markowanga** [goose3/goose3#172]
For version 3.1.14, Python 3.10, macOS / Ubuntu

Code:
```python
from goose3 import Goose

if __name__ == '__main__':
    Goose().extract('https://radiokielce.pl/1054846/gospodynie-beda-rywalizowac-o-najlepsza-potrawe/')
```

Result:
```
Publish date ['2023-05-28T09:41:17+02:00', '2023-05-28T09:41:17+02:00'] could not be resolved to UTC
Traceback (most recent call last):
  File "/Users/marcinwatroba/Desktop/MY_PROJECTS/race_position_checker/main.py", line 4, in <module>
    Goose().extract('https://radiokielce.pl/1054846/gospodynie-beda-rywalizowac-o-najlepsza-potrawe/')
  File "/Users/marcinwatroba/opt/miniconda3/envs/race_position_checker/lib/python3.10/site-packages/goose3/__init__.py", line 125, in extract
    return self.__crawl(crawl_candidate)
  File "/Users/marcinwatroba/opt/miniconda3/envs/race_position_checker/lib/python3.10/site-packages/goose3/__init__.py", line 153, in __crawl
    return crawler_wrapper(self.config.parser_class, parsers, crawl_candidate)
  File "/Users/marcinwatroba/opt/miniconda3/envs/race_position_checker/lib/python3.10/site-packages/goose3/__init__.py", line 141, in crawler_wrapper
    article = crawler.crawl(crawl_candidate)
  File "/Users/marcinwatroba/opt/miniconda3/envs/race_position_checker/lib/python3.10/site-packages/goose3/crawler.py", line 135, in crawl
    return self.process(raw_html, parse_candidate.url, parse_candidate.link_hash)
  File "/Users/marcinwatroba/opt/miniconda3/envs/race_position_checker/lib/python3.10/site-packages/goose3/crawler.py", line 186, in process
    self.article._title = self.title_extractor.extract()
  File "/Users/marcinwatroba/opt/miniconda3/envs/race_position_checker/lib/python3.10/site-packages/goose3/extractors/title.py", line 103, in extract
    return self.get_title()
  File "/Users/marcinwatroba/opt/miniconda3/envs/race_position_checker/lib/python3.10/site-packages/goose3/extractors/title.py", line 84, in get_title
    return self.clean_title(self.article.opengraph["title"])
  File "/Users/marcinwatroba/opt/miniconda3/envs/race_position_checker/lib/python3.10/site-packages/goose3/extractors/title.py", line 37, in clean_title
    title = pattern.sub("", title).strip()
TypeError: expected string or bytes-like object

Process finished with exit code 1
```

**Comment by barrust** [comment]
Good catch. I just checked and it is an issue in the main code branch. It seems to be when the opengraph parser returns a list instead of a single string for the title. 

I pushed a [PR](https://github.com/goose3/goose3/pull/173) that should fix the issue along with tests to ensure future changes do not bring it back.
