### ISSUE TITLE
Error on invalid file

### ISSUE THREAD

**Issue by deg** [goose3/goose3#187]
I'm not sure this is a valid issue; reporting it just in case...

I'm running Goose on a large set of web pages, a few of which are accidentally pdf files.
In most cases, this gives the expected nonsensical results, with Goose trying to pull text from the raw pdf naively.

But, one file throws an exception:

```
Goose().extract("https://dspace.mit.edu/bitstream/handle/1721.1/5864/AIM-187.pdf")
```

```
Parser lxml failed to parse the content
Parser soup failed to parse the content
Traceback (most recent call last):

...

  File "/Users/deg/Documents/hobby/vuagain23/va_backend/.venv/lib/python3.11/site-packages/goose3/parsers.py", line 53, in fromstring
    encoding = get_encodings_from_content(html)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deg/Documents/hobby/vuagain23/va_backend/.venv/lib/python3.11/site-packages/goose3/text.py", line 40, in get_encodings_from_content
    content = content.decode()
              ^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 10: invalid continuation byte
...
```

So:

1) Is it reasonable and expected that callers of Goose() should be responsible for catching deep errors like these?
2) Obviously, I really don't want to run Goose on PDF files. But (short of trusting the URL's file extension, or doing the full HEAD/GET/errorHandling dance) I have no easy way to recognize the problematic files. Does Goose offer any way to short-circuit inappropriate files?

**Comment by barrust** [comment]
This is currently out of scope for goose3 and it is the user's responsibility to catch these errors. If there are suggestions on how goose3 could control this, PRs and example code would be helpful!
