### ISSUE TITLE
Relative image paths not working?...

### ISSUE THREAD

**Issue by pavitrakumar78** [goose3/goose3#21]
Hi,

I tried these links below:
```
from goose3 import Goose
g = Goose({'browser_user_agent': 'Mozilla'})

article = g.extract(url='https://www.cryptocompare.com/') #........[1]

article = g.extract(url='https://www.google.com/admob/businesskit/from-an-idea-to-an-app/') #........[2]
```
I get the following errors:
```
(for [1])
MissingSchema: Invalid URL 'https:/media/12318336/mnz.png?width=350': No schema supplied. Perhaps you meant http://https:/media/12318336/mnz.png?width=350?

(for [2])
MissingSchema: Invalid URL 'https:/admob/images/businesskit/interviews/marvinpaul.jpg': No schema supplied. Perhaps you meant http://https:/admob/images/businesskit/interviews/marvinpaul.jpg?
```
Perhaps the output should have been the following?...
```
(for[1])
https://www.cryptocompare.com/media/12318336/mnz.png?width=350

(for [2])
https://www.google.com/admob/images/businesskit/interviews/marvinpaul.jpg?
```

System info:
Windows 10
Python 3.5
goose3 installed from here: https://github.com/goose3/goose3
(The one given in the instructions is an old repo I guess?...)

Full traceback for [2]:

```
Traceback (most recent call last):

  File "<ipython-input-15-94ebba58016d>", line 3, in <module>
    article = g.extract(url='https://www.google.com/admob/businesskit/from-an-idea-to-an-app/')

  File "D:\Applications\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\goose3-3.0.6-py3.5.egg\goose3\__init__.py", line 81, in extract
    return self.crawl(cc)

  File "D:\Applications\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\goose3-3.0.6-py3.5.egg\goose3\__init__.py", line 97, in crawl
    raise e

  File "D:\Applications\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\goose3-3.0.6-py3.5.egg\goose3\__init__.py", line 91, in crawl
    article = crawler.crawl(crawl_candidate)

  File "D:\Applications\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\goose3-3.0.6-py3.5.egg\goose3\crawler.py", line 120, in crawl
    return self.process(raw_html, parse_candidate.url, parse_candidate.link_hash)

  File "D:\Applications\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\goose3-3.0.6-py3.5.egg\goose3\crawler.py", line 190, in process
    self.get_image()

  File "D:\Applications\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\goose3-3.0.6-py3.5.egg\goose3\crawler.py", line 212, in get_image
    self.article.top_image = self.image_extractor.get_best_image(doc, top_node)

  File "D:\Applications\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\goose3-3.0.6-py3.5.egg\goose3\extractors\images.py", line 82, in get_best_image
    image = self.check_large_images(topNode, 0, 0)

  File "D:\Applications\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\goose3-3.0.6-py3.5.egg\goose3\extractors\images.py", line 135, in check_large_images
    depth_obj.parent_depth, depth_obj.sibling_depth)

  File "D:\Applications\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\goose3-3.0.6-py3.5.egg\goose3\extractors\images.py", line 116, in check_large_images
    good_images = self.get_image_candidates(node)

  File "D:\Applications\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\goose3-3.0.6-py3.5.egg\goose3\extractors\images.py", line 278, in get_image_candidates
    good_images = self.get_images_bytesize_match(filtered_images)

  File "D:\Applications\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\goose3-3.0.6-py3.5.egg\goose3\extractors\images.py", line 295, in get_images_bytesize_match
    local_image = self.get_local_image(src)

  File "D:\Applications\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\goose3-3.0.6-py3.5.egg\goose3\extractors\images.py", line 338, in get_local_image
    return ImageUtils.store_image(self.fetcher, self.link_hash, src, self.config)

  File "D:\Applications\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\goose3-3.0.6-py3.5.egg\goose3\utils\images.py", line 66, in store_image
    data = http_client.fetch(src)

  File "D:\Applications\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\goose3-3.0.6-py3.5.egg\goose3\network.py", line 54, in fetch
    response = self._connection.get(url, timeout=self.config.http_timeout, headers=self.headers)

  File "D:\Applications\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)

  File "D:\Applications\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\requests\sessions.py", line 461, in request
    prep = self.prepare_request(req)

  File "D:\Applications\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\requests\sessions.py", line 394, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),

  File "D:\Applications\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\requests\models.py", line 294, in prepare
    self.prepare_url(url, params)

  File "D:\Applications\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\requests\models.py", line 354, in prepare_url
    raise MissingSchema(error)

MissingSchema: Invalid URL 'https:/admob/images/businesskit/interviews/marvinpaul.jpg': No schema supplied. Perhaps you meant http://https:/admob/images/businesskit/interviews/marvinpaul.jpg?
```

**Comment by barrust** [comment]
@pavitrakumar78 I had a hunch that relative image URLs were not working but hadn't run into the issue myself. As such, I was already working on tracking down the root of the problem. Your examples helped immensely in tracking it down!

**Comment by pavitrakumar78** [comment]
@barrust hey! Thanks for quick reply and fix! Tested your changes on my system and images are fetched fine for the links I posted. Should I leave this issue open until the changes have been merged?

**Comment by barrust** [comment]
I'm glad that it worked! I would leave this open until it gets merged so that it doesn't get lost!
