### ISSUE TITLE
Python 3.6 compatibility error 

### ISSUE THREAD

**Issue by Guitaricet** [goose3/goose3#5]
import goose3

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/anaconda3/lib/python3.6/site-packages/goose3/__init__.py", line 26, in <module>
    from goose3.configuration import Configuration
  File "/Users/user/anaconda3/lib/python3.6/site-packages/goose3/configuration.py", line 28, in <module>
    from goose3.text import StopWords
  File "/Users/user/anaconda3/lib/python3.6/site-packages/goose3/text.py", line 125, in <module>
    class StopWords(object):
  File "/Users/user/anaconda3/lib/python3.6/site-packages/goose3/text.py", line 127, in StopWords
    PUNCTUATION = re.compile("[^\\p{Ll}\\p{Lu}\\p{Lt}\\p{Lo}\\p{Nd}\\p{Pc}\\s]")
  File "/Users/user/anaconda3/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/Users/user/anaconda3/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Users/user/anaconda3/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/Users/user/anaconda3/lib/python3.6/sre_parse.py", line 856, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, False)
  File "/Users/user/anaconda3/lib/python3.6/sre_parse.py", line 415, in _parse_sub
    itemsappend(_parse(source, state, verbose))
  File "/Users/user/anaconda3/lib/python3.6/sre_parse.py", line 526, in _parse
    code1 = _class_escape(source, this)
  File "/Users/user/anaconda3/lib/python3.6/sre_parse.py", line 336, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
sre_constants.error: bad escape \p at position 2

Works well in python3.5, but not python3.6

The issue looks very much like this one:
https://github.com/facelessuser/backrefs/issues/2

**Comment by geovedi** [comment]
as workaround, `regex` module can be used instead of builtin `re`.

**Comment by lababidi** [comment]
Would either of you @geovedi @Guitaricet like to contribute a Pull Request to fix this issue?

**Comment by serhiy-storchaka** [comment]
The `re` module doesn't support the `\p{...}` syntax. The pattern `"[^\\p{Ll}\\p{Lu}\\p{Lt}\\p{Lo}\\p{Nd}\\p{Pc}\\s]"` is interpreted as `"[^LNP\\\\cdlopstu{}]"` (any character except `"LNP\\cdlopstu{}"`). If you want to use that regular expression properly you must use the `regex` module.

But it seems that that regular expression is not used and can be removed.

**Comment by fomiciov** [comment]
Removing this regex actually solves the issue.

**Comment by lababidi** [comment]
#6 closes this

**Comment by juanmanubens** [comment]
Had the same issue, was able to solve it like this:

1) Reinstall regex, supersede any old  version
`conda install -c conda-forge regex`

2) In my python code, I was using this:
`import re`

Replace that with this:
`import regex as re`

Everything else equal, you should be back to normal
