### ISSUE TITLE
UnicodeDecodeError: invalid continuation byte

### ISSUE THREAD

**Issue by dust0x** [goose3/goose3#74]
When running a simple extract on [this website](http://wiitalia.it), the program throws a `UnicodeDecodeError`. This exception has not been observed so far for any of the other websites in my dataset.
The traceback is given below:
```
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/goose3/__init__.py", line 128, in crawler_wrapper
    article = crawler.crawl(crawl_candidate)
  File "/home/user/anaconda3/lib/python3.6/site-packages/goose3/crawler.py", line 128, in crawl
    return self.process(raw_html, parse_candidate.url, parse_candidate.link_hash)
  File "/home/user/anaconda3/lib/python3.6/site-packages/goose3/crawler.py", line 169, in process
    self.article._tags = self.tags_extractor.extract()
  File "/home/user/anaconda3/lib/python3.6/site-packages/goose3/extractors/tags.py", line 47, in extract
    tag = self.parser.getText(elm)
  File "/home/user/anaconda3/lib/python3.6/site-packages/goose3/parsers.py", line 186, in getText
    txts = [i for i in node.itertext()]
  File "/home/user/anaconda3/lib/python3.6/site-packages/goose3/parsers.py", line 186, in <listcomp>
    txts = [i for i in node.itertext()]
  File "src/lxml/etree.pyx", line 2963, in lxml.etree.ElementTextIterator.__next__
  File "src/lxml/etree.pyx", line 1033, in lxml.etree._Element.tail.__get__
  File "src/lxml/apihelpers.pxi", line 670, in lxml.etree._collectText
  File "src/lxml/apihelpers.pxi", line 1405, in lxml.etree.funicode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 8: invalid continuation byte
```

And the code to reproduce this error:
```
from goose3 import Goose

def main():
    article = g.extract(url='http://wiitalia.it')
    print(article.title)

g = Goose()

if __name__ == '__main__': main()
```
Any ideas as to what's going on here?

**Comment by dust0x** [comment]
@barrust I believe that this is a related error, reproducible with the following website `aquaticplantcentral.com`

```
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/goose3-3.1.4-py3.6.egg/goose3/__init__.py", line 128, in crawler_wrapper
    article = crawler.crawl(crawl_candidate)
  File "/home/user/anaconda3/lib/python3.6/site-packages/goose3-3.1.4-py3.6.egg/goose3/crawler.py", line 132, in crawl
    return self.process(raw_html, parse_candidate.url, parse_candidate.link_hash)
  File "/home/user/anaconda3/lib/python3.6/site-packages/goose3-3.1.4-py3.6.egg/goose3/crawler.py", line 204, in process
    self.article._top_node = self.extractor.calculate_best_node(doc)
  File "/home/user/anaconda3/lib/python3.6/site-packages/goose3-3.1.4-py3.6.egg/goose3/extractors/content.py", line 88, in calculate_best_node
    text_node = self.parser.getText(node)
  File "/home/user/anaconda3/lib/python3.6/site-packages/goose3-3.1.4-py3.6.egg/goose3/parsers.py", line 186, in getText
    txts = [i for i in node.itertext()]
  File "/home/user/anaconda3/lib/python3.6/site-packages/goose3-3.1.4-py3.6.egg/goose3/parsers.py", line 186, in <listcomp>
    txts = [i for i in node.itertext()]
  File "src/lxml/etree.pyx", line 2961, in lxml.etree.ElementTextIterator.__next__
  File "src/lxml/etree.pyx", line 1014, in lxml.etree._Element.text.__get__
  File "src/lxml/apihelpers.pxi", line 670, in lxml.etree._collectText
  File "src/lxml/apihelpers.pxi", line 1405, in lxml.etree.funicode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 109: invalid start byte
```
My current goose3 version is installed from source.

**Comment by barrust** [comment]
Yep, great catch. It looks like another place where there can be a mismatch. For https://www.aquaticplantcentral.com/84724/new-large-pearl-grass it looks like it is that the headers say that it is using a different encoding than what is actually used (probably default). I should have something later today in a PR.
